DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS genres;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL,
                       login VARCHAR(255) NOT NULL,
                       name VARCHAR(255),
                       birthday DATE
);

CREATE TABLE films (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(500),
                       release_date DATE,
                       duration INTEGER NOT NULL,
                       mpa_id INTEGER
);

CREATE TABLE friendships (
                             user_id BIGINT NOT NULL,
                             friend_id BIGINT NOT NULL,
                             status VARCHAR(20) NOT NULL,
                             PRIMARY KEY (user_id, friend_id),
                             CONSTRAINT fk_friendships_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                             CONSTRAINT fk_friendships_friend FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE likes (
                       film_id BIGINT NOT NULL,
                       user_id BIGINT NOT NULL,
                       PRIMARY KEY (film_id, user_id),
                       CONSTRAINT fk_likes_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
                       CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE mpa (
                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(50) NOT NULL
);

CREATE TABLE genres (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(50) NOT NULL
);

CREATE TABLE film_genres (
                             film_id BIGINT NOT NULL,
                             genre_id INTEGER NOT NULL,
                             PRIMARY KEY (film_id, genre_id),
                             CONSTRAINT fk_film_genres_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
                             CONSTRAINT fk_film_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);